### PR TITLE
Update service name translation

### PR DESCRIPTION
**Pull request by v-chenyh**
Service name updated from "用于MySQL的Azure数据库“ to ”Azure Database for MySQL"

### CODE REVIEW

**Comment by v-chenyh** [comment]
#sign-off

**Comment by CeciAc** [comment]
Hi **@v-chenyh**  we are still discussing this issue, will update the decision later soon. 
_Thanks for your support,
Microsoft C&E Localization Team_

**Comment by v-radelg** [comment]
@v-chenyh  Thank you for your feedback and suggestion! 
		
We found reasons which are not fully aligned to our acceptance criterial, I am closing this PR. 
		
Microsoft C&E Localization Team

**Comment by v-chenyh** [comment]
@v-radelg Can you please explain the exact reason behind of closing this PR without merge?

**Pull request closed without merging**
